### ISSUE TITLE
create a search-by-city page

### ISSUE THREAD

**Issue by victor-o-silva** [victor-o-silva/parkour_spots#42]
check http://django-gis-brasil.readthedocs.org/en/latest/

**Comment by tgonzales** [comment]
unsubscribe me

On 9 January 2015 at 16:17, VIctor Oliveira da Silva <
notifications@github.com> wrote:

> check http://django-gis-brasil.readthedocs.org/en/latest/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/victor-o-silva/parkour_spots/issues/42>.
>



-- 
Melissa Morris
CEO | *Network Locum*


0203 6039242 | 07827233804

**Comment by victor-o-silva** [comment]
I can't. You started "watching" the repository, so you have to "unwatch" it yourself.

**Comment by tgonzales** [comment]
no i didnt!
i have nothing to do with your company

On 9 January 2015 at 18:15, VIctor Oliveira da Silva <
notifications@github.com> wrote:

> I can't. You started "watching" the repository, so you have to "unwatch"
> it yourself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/victor-o-silva/parkour_spots/issues/42#issuecomment-69374479>
> .
>



-- 
Melissa Morris
CEO | *Network Locum*


0203 6039242 | 07827233804

**Comment by victor-o-silva** [comment]
Maybe GitHub made you a watcher when you forked the repo
